spring:
  application:
    name: mancala
  data:
    mongodb:
      host: mongodb
      port: 27017

server:
  port: 8080

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html

logging:
  level:
    org.springframework.web: DEBUG
    com.bol.mancala: INFO