apiVersion: apps/v1
kind: Deployment
metadata:
  name: webflux-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webflux-app
  template:
    metadata:
      labels:
        app: webflux-app
    spec:
      containers:
        - name: webflux-app
          image: webflux-app:latest
          ports:
            - containerPort: 8080
          env:
            - name: SPRING_DATA_MONGODB_URI
              value: "mongodb://mongo:27017/testdb"