apiVersion: apps/v1
kind: Deployment
metadata:
  name: mancala-app-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mancala-app
  template:
    metadata:
      labels:
        app: mancala-app
    spec:
      containers:
        - name: mancala-app
          image: soundar50/mancala-app
          ports:
            - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: mancala-app-service
spec:
  selector:
    app: mancala-app
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
